export const AMBIGUOUS_LOCATION = '200';
export const MISSPELLED_LOCATION = '202';
export const LISTINGS_OF_ONE_UNAMBIGUOUS_LOCATION = '100';
export const LISTINGS_OF_BEST_AMBIGUOUS_LOCATION = '101';
export const LISTINGS_LARGE_LOCATION = '110';